### ISSUE TITLE
Activations are added in twice in BlockOutputWrapper

### ISSUE THREAD

**Issue by chanind** [nrimsky/CAA#2]
It appears that `BlockOutputWrapper` adds activations to the output twice, which looks like a bug. [augmented_output](https://github.com/nrimsky/SycophancySteering/blob/main/llama_wrapper.py#L69) contains the steering vector added into the outputs at the correctly masked token positions according to `add_only_after_end_str`. However, then on [line 76](https://github.com/nrimsky/SycophancySteering/blob/main/llama_wrapper.py#L76), the steering vector is added in a second time, this time at every token position:

```python
output = (augmented_output + self.add_activations,) + output[1:]
```

Is this desired behavior? It seems like line 76 should be the following, since the steering vector is already included in `augmented_output` :

```python
output = (augmented_output,) + output[1:]
```

Currently the response tokens get the steering vector added twice, and all other tokens get the steering vector added once as a result of this, if I understand the code correctly.

**Comment by nrimsky** [comment]
Ah yes spotted this today

Rerunning experiments and fixing bugs this week, will update arxiv and codebase soon 👍

**Comment by dtch1997** [comment]
Great catch @chanind ! 

@nrimsky : david and I are developing a new `steering-vectors` library to easily run CAA and other related approaches on HF models. https://github.com/steering-vectors/steering-vectors 

We're currently attempting to reproduce Figures 6 and 11 from the paper with our own codebase, and really appreciate how responsive you are!

**Comment by nrimsky** [comment]
I fixed this bug on this branch but I am working on the `v2` branch with more global updates / better experimental methods. Am in the process of re-running things also.

**Comment by nrimsky** [comment]
changes merged
