### ISSUE TITLE
How is this code licensed?

### ISSUE THREAD

**Issue by chanind** [nrimsky/CAA#5]
Adding a LICENSE file to the repo would make it clear what the license for the code is, and where/if it's allowed to use this code in other places.

**Comment by nrimsky** [comment]
Will do in the new version (wip on branch v2)

**Comment by chanind** [comment]
The reason I ask is because I want to add a pytest test case which asserts that the behavior of a steering vectors library I'm working on behaves identically to this original CAA implementation. In order to test this, I copied some of the code from this repo into the tests folder. The library won't include your code when installed from PyPI, but will have it in the test dir in the git repo. Is this OK usage?

The test case in question is [here](https://github.com/steering-vectors/steering-vectors/pull/3/files#diff-abbd58a85426aa99b8d26b792b58b55de97e840e2bea51c83218b04719cd377fR31), and the pull request adding the code is https://github.com/steering-vectors/steering-vectors/pull/3.

If this isn't OK I'll delete the CAA code from the PR and remove the test case.

**Comment by nrimsky** [comment]
no problem at all!

the code is free for any reuse

in papers that make heavy use of this code it would be good to cite the CAA paper

**Comment by chanind** [comment]
Amazing, thank you so much! If we get a paper written CAA will definitely be cited!

**Comment by nrimsky** [comment]
MIT license added
